PerformanceTest.cs : PerformanceTest.cs ../AVLTree/AVLTree.cs ../BinarySearchTree/BinarySearchTree.cs ../AVLTree/ISet.cs
	csc PerformanceTest.cs ../AVLTree/AVLTree.cs ../BinarySearchTree/BinarySearchTree.cs ../AVLTree/ISet.cs
